SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.st limit 100;

SELECT *
FROM DBT_DEMO_DB.RAW.STG_RAW_LINE_ITEMS limit 100;


SELECT *
FROM INFORMATICA_DEMO_DB.DEV.INT_ORDER_ITEMS
where order_key = 2135463;