name: dbt_project
version: 1.0.0
config-version: 2
profile: dbt_project
model-paths:
  - models
test-paths:
  - tests
macro-paths:
  - macros
models:
    dbt_project:
        staging:
            schema: raw
            +materialized: view
        marts:
            +materialized: table
