dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DBT_DEMO_DB
      schema: DEV
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: PROD_DBT_DEMO_DB
      schema: prod
      warehouse: COMPUTE_WH